/* 
  Sketch generated by the Arduino IoT Cloud Thing "ModelHome"
  https://create.arduino.cc/cloud/things/94d0dc15-9de2-4f23-9efa-684706e721fb 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool ac_on;
  bool heater_on;
  bool light_on;
  bool tv_on;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// Define pins
#define pinHeater 5 //D1
#define pinAC 4     //D2
#define pinTV 0     //D3
#define pinLight 2  //D4

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  //Init pins
  pinMode(pinHeater, OUTPUT);
  pinMode(pinAC, OUTPUT);
  pinMode(pinTV, OUTPUT);
  pinMode(pinLight, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

  // Heater
  if (heater_on) {
    digitalWrite(pinHeater,HIGH); 
  }
  else {
    digitalWrite(pinHeater,LOW); 
  }

  // Aircon
  if (ac_on) {
    digitalWrite(pinAC,HIGH); 
  }
  else {
    digitalWrite(pinAC,LOW); 
  }

  // TV

  if (tv_on) {
    digitalWrite(pinTV,HIGH); 
  }
  else {
    digitalWrite(pinTV,LOW); 
  }

  // Light

  if (light_on) {
    digitalWrite(pinLight,HIGH); 
  }
  else {
    digitalWrite(pinLight,LOW); 
  }
  


  
  delay(350);
}



/*
  Since HeaterOn is READ_WRITE variable, onHeaterOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHeaterOnChange()  {
  // Add your code here to act upon HeaterOn change
  Serial.println("Heater updated!");
}

/*
  Since AcOn is READ_WRITE variable, onAcOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAcOnChange()  {
  // Add your code here to act upon AcOn change
  Serial.println("AC updated!");
}

/*
  Since LightOn is READ_WRITE variable, onLightOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightOnChange()  {
  // Add your code here to act upon LightOn change
  Serial.println("Light updated!");
}

/*
  Since TvOn is READ_WRITE variable, onTvOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTvOnChange()  {
  // Add your code here to act upon TvOn change
  Serial.println("TV updated!");
}