/* 
  Sketch generated by the Arduino IoT Cloud Thing "Switch"
  https://create.arduino.cc/cloud/things/727aea7e-5c7f-4679-bc0b-ff91617fbd78 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool heater_on;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Button.h>

// Define pins
Button button(4);    //D2
#define pinLED 2     //D4

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  button.begin();
  pinMode(pinLED, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  
  if (heater_on) {
    digitalWrite(pinLED,HIGH); 
  }
  else {
    digitalWrite(pinLED,LOW); 
  }
  
  
  if (button.pressed()){
		Serial.println("Button pressed");
		heater_on = !heater_on;
		Serial.println("Heating toggled:");
		Serial.println(heater_on);
  }

}


/*
  Since HeaterOn is READ_WRITE variable, onHeaterOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHeaterOnChange()  {
  // Add your code here to act upon HeaterOn change
}